rollout unnamedRollout "Untitled" width:400 height:500
(
	button 'btn1' "Start Building" pos:[141,158] width:90 height:19 align:#left
	radioButtons 'rdo2' "Modules:" pos:[108,20] width:68 height:78 labels:#(Wall, Window, Door, Empty) align:#left
	button 'btn2' "Configuration" pos:[217,21] width:73 height:20 align:#left
	button 'btn3' "Configuration" pos:[215,42] width:73 height:20 align:#left
	button 'btn4' "Configuration" pos:[219,63] width:73 height:20 align:#left
	button 'btn5' "Configuration" pos:[220,83] width:73 height:20 align:#left
)
